### ISSUE TITLE
Analysis of e-books in Mobi format

### ISSUE THREAD

**Issue by mumujj** [vers-one/EpubReader#100]
Have you ever done e-book parsing in Mobi format? Or have you ever known about it? If so, can you provide a detailed description?

**Comment by vers-one** [comment]
Unfortunately, I have no experience with parsing `.mobi` files.

**Comment by mumujj** [comment]
**********************************
IMPORTANT NOTICE: This email is from a third-party vendor and its personnel who provide services to Lenovo,and this email is not legally binding on Lenovo. Any Lenovo commitments should only be included in a formal contract signed between the two parties. Lenovo shall not be liable for any damages of any kind in any form whatsoever caused by this email. Any opinions expressed by individuals in this email neither represent nor reflect Lenovo's. This email and any documents sent with it may contain confidential information and are protected by the privileges of lawyers and clients. This message is only read and used by the intended recipients. Unauthorized viewing, use, disclosure or distribution of this email or the documents sent with it is strictly prohibited. If you are not the intended recipient, please do not read or save this message, and please delete this message permanently and destroy any printed copies. Thank you.
重要通知：本电子邮件来自于向联想提供服务的第三方供应商及其人员，且该邮件并不对联想发生法律约束力。 联想的任何承诺均应仅包含在双方之间相互签署的正式合同中。 对于本邮件无论基于何种原因导致的无论何种形式的任何损失，联想均不承担责任。个人在本邮件中表达的任何观点既不代表也不反映联想的观点。 本邮件和与之一起发送的任何文件均可能含有保密信息，并受律师和客户特权保护。本邮件仅供指定的收件人阅读和使用。严禁对本邮件或与之一起发送的文件进行未经授权的查看、使用、披露或分发。 如果您不是指定的收件人，请勿阅读或保存本邮件，并请永久删除本邮件并销毁任何打印副本。谢谢。
**********************************



  Thank you for your answer。
________________________________
发件人: vers-one ***@***.***>
发送时间: 2023年7月30日 1:19
收件人: vers-one/EpubReader ***@***.***>
抄送: Jiajuan JJ1 Mou ***@***.***>; Author ***@***.***>
主题: [External] Re: [vers-one/EpubReader] Analysis of e-books in Mobi format (Issue #100)


Closed #100<https://github.com/vers-one/EpubReader/issues/100> as completed.

―
