### ISSUE TITLE
Add support for BMP image files

### ISSUE THREAD

**Issue by songshizhao** [vers-one/EpubReader#102]
## Description
VersOne.Epub.EpubPackageException:
            using (EpubBookRef bookRef = EpubReader.OpenBook(filePath))
            {
                Debug.WriteLine("Navigation:");
                foreach (EpubNavigationItemRef navigationItemRef in bookRef.GetNavigation())
                {
                    PrintNavigationItem(navigationItemRef, 0);
                }
            }
Incorrect EPUB manifest: item with href = "cover.bmp" is missing.

## Sample EPUB file
downloaded this webpage : https://www.qinkan.net/book/2251.html
(download button is at bottom of this page)
## EPUB specification link
none

## Additional context

This book may dont have a cover img, can I ignore this error and read the content? 
I update this book to some online reader (https://reader.960960.xyz/#/manager/home),there is cover img existing.

**Comment by vers-one** [comment]
EpubReader currently doesn't recognize *.bmp files as images (EPUB 2 specification [doesn't include it](https://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section1.3.7) in the list of supported file formats) but I'll add support for *.bmp files in the next release.

For now, the only way to make this file work with EpubReader is to remove this line:
```
<meta name="cover" content="cover"/>
```
from the `OEBPS\content.opf` file inside the EPUB file.

**Comment by songshizhao** [comment]
ok , 👌

**Comment by vers-one** [comment]
Sorry it took so long. This is implemented in [3.3.2](https://github.com/vers-one/EpubReader/releases/tag/v3.3.2).
