### ISSUE TITLE
How to pull specific text

### ISSUE THREAD

**Issue by quatre432** [vers-one/EpubReader#103]
Hey guys i have been trying to figure this out for a couple of days, love the reader works good im trying to figure out with agilty pack or other how to pull a certain string of text out of the book, 

the text in question is in bold font and stands out from the rest of the book 

the content looks like this 

`<p class="first2"> <b class="calibre3"> Text Here </b> </p>`

all the text i have seen that i want to be stripped is in class calibre3 and in tag b but i cant get anything to just pull that data any help would be awesome

**Comment by vers-one** [comment]
Html Agility Pack can do that. I would suggest checking [its repository](https://github.com/zzzprojects/html-agility-pack) and documentation or post a question in the [Html Agility Pack section](https://stackoverflow.com/questions/tagged/html-agility-pack) on StackOverflow.
