### ISSUE TITLE
How to write EPUB files?

### ISSUE THREAD

**Issue by itchangc** [vers-one/EpubReader#105]
How to write EPUB files?
How to write EPUB files?
How to write EPUB files?

**Comment by kaazha** [comment]
An EPUB file is basically a zip package that comprises of:
- an OPF package file (.opf extension)
- xhtml files for each chapter of the book 
- [optional] a toc (table of contents file) 
- [optional] a title page (xhtml) file
- [optional] stylesheets, images, scripts

The OPF file has a manifest section (xml element/node) that contains links to each chapter file and the other optional files that are referenced from the book contents
Just put all these files inside a folder named OPS and compress the folder and change the extension to ".epub" and you are all set! I will drop a sample if you want.

**Comment by itchangc** [comment]
可以给我一个demo吗？非常感谢



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2023 20:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [vers-one/EpubReader] How to write EPUB files? (Issue #105) |

An EPUB file is basically a zip package that comprises of:

an OPF package file (.opf extension)
xhtml files for each chapter of the book
[optional] a toc (table of contents file)
[optional] a title page (xhtml) file
[optional] stylesheets, images, scripts

The OPF file has a manifest section (xml element/node) that contains links to each chapter file and the other optional files that are referenced from the book contents
Just put all these files inside a folder named OPS and compress the folder and change the extension to ".epub" and you are all set! I will drop a sample if you want.

**Comment by itchangc** [comment]
Can you provide me with a program? Thank you very much. I am currently at a loss

**Comment by itchangc** [comment]
Can you provide me with a program? Thank you very much. I am currently at a loss



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2023 20:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [vers-one/EpubReader] How to write EPUB files? (Issue #105) |

An EPUB file is basically a zip package that comprises of:

an OPF package file (.opf extension)
xhtml files for each chapter of the book
[optional] a toc (table of contents file)
[optional] a title page (xhtml) file
[optional] stylesheets, images, scripts

The OPF file has a manifest section (xml element/node) that contains links to each chapter file and the other optional files that are referenced from the book contents
Just put all these files inside a folder named OPS and compress the folder and change the extension to ".epub" and you are all set! I will drop a sample if you want.

**Comment by vers-one** [comment]
EpubReader [can't write EPUB files](https://os.vers.one/EpubReader/faq/index.html#how-to-write-epub-files). It can only read them.
