### ISSUE TITLE
Parse <nav> elements nested in other HTML elements in EPUB 3 navigation documents

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#106]
I'm debugging a book where the Navigation items aren't loading for Table of Contents generation. 

This book has a TOC file within it, I see a line in the manifest:
<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
<item id="xtoc" href="toc.xhtml" media-type="application/xhtml+xml" properties="nav"/>

But the GetNavigationAsync() returns nothing. Maybe I have a misunderstanding of the point of this API? 

Here are the needed files:
[content.opf.txt](https://github.com/vers-one/EpubReader/files/13063359/content.opf.txt)
[toc.ncx.txt](https://github.com/vers-one/EpubReader/files/13063360/toc.ncx.txt)
[toc.xhtml.txt](https://github.com/vers-one/EpubReader/files/13063361/toc.xhtml.txt)

**Comment by vers-one** [comment]
When EpubReader parses **toc.xhtml** file, it expects to find the `<nav epub:type="toc">` element [among the children](https://github.com/vers-one/EpubReader/blob/8b7376de6a3f00eb4659acb1bcbf1d25adf07cb0/Source/VersOne.Epub/Readers/Epub3NavDocumentReader.cs#L53) of the `<body>` element. In this case, the `<nav>` element is wrapped in `<div>`, so EpubReader can't find it.

Interestingly, EPUB specification does not specify whether `<nav>` elements can be wrapped in other elements. It also doesn't prohibit nesting one `<nav>` into another `<nav>`. I'll add support for this case in the next release.

**Comment by vers-one** [comment]
Sorry it took so long. This is fixed in [3.3.2](https://github.com/vers-one/EpubReader/releases/tag/v3.3.2).
