### ISSUE TITLE
Cannot create an instance of "BookHtmlContent"

### ISSUE THREAD

**Issue by fly1062768879** [vers-one/EpubReader#12]
I have encounterd a proble, In the BookView.xmal, It do not recongnize "BookHtmmlContent"? what is it?
![tim 20180314150019](https://user-images.githubusercontent.com/28781611/37387705-7949e9ae-2798-11e8-933a-2f843c5b5a7d.png)

**Comment by fly1062768879** [comment]
![image](https://user-images.githubusercontent.com/28781611/37577167-51ae1196-2b6b-11e8-9a08-717106d43850.png)

Yes, build it no prblem,but when run it , it encoutered an exception, but remove this controll ,it disappears . I cannot figuer out what this exception is

**Comment by vers-one** [comment]
Click on the "View Deails" link to open the exception details window and look at the inner exception.

**Comment by vers-one** [comment]
Closed due to inactivity.
