### ISSUE TITLE
Issue parsing ePub files

### ISSUE THREAD

**Issue by tjenniges** [vers-one/EpubReader#14]
I have attached 3 ePub files that fail to be parsed by ePubReader.

I found these files in the wild, by google searching by file type to build up a ePub test
dataset to test ePubReader against.

I have other files that fail too but for same reasons as the ones attached (TOC error, etc)

Good job so far. 

Thanks.
[childrens-literature.zip](https://github.com/vers-one/EpubReader/files/2211700/childrens-literature.zip)
[GhV-oeb-page.zip](https://github.com/vers-one/EpubReader/files/2211701/GhV-oeb-page.zip)

[CF General.zip](https://github.com/vers-one/EpubReader/files/2211708/CF.General.zip)

**Comment by tjenniges** [comment]
Thanks a lot. If I find more EPUB 3 files with issues I will be sure to send them to you for your testing dataset

**Comment by vers-one** [comment]
Sorry for a delay. Working on this.

**Comment by tjenniges** [comment]
Ok. Let me know when finished and I will run tests against an epub dataset I have.

**Comment by vers-one** [comment]
I've made a preliminary version with the improved support for EPUB 3 files. It can be found in the `epub3` branch of the repository. I've also added an option to the `NetCoreDemo` application to test the library by opening all epub files in a directory (see the `3. Test the library by reading all EPUB files from a directory` option there). You can run it on your epub dataset.

This is a preliminary version and it is available as the source code only. There are still [some things](https://github.com/vers-one/EpubReader/issues/18) I plan to finish before making a new release.

**Comment by vers-one** [comment]
I've released the version 3.0.0 of the library with the better EPUB 3 support. Please reopen this issue if you find any other problems with the EPUB 3 files.
