### ISSUE TITLE
Font mime-type missing

### ISSUE THREAD

**Issue by willroscoe** [vers-one/EpubReader#16]
Hi, Thanks for the great project. I have some epub books where the ttf fonts have a mime-type of "application/x-font-truetype". I notice this mime-type is not included in the  /Readers/ContentReaders.cs file. As a result, these fonts are not included in the EpubContent.Fonts list - they are being classed as EpubContentType.OTHER.

The fonts also appear to have 'ccs/' prefixed to their path (as does the .css file) even though in the epub archive manifest there is no css folder (the .css file is in the 'Styles' folder). Could you explain why this is?
Many thanks,
Will

**Comment by vers-one** [comment]
application/x-font-truetype MIME type support has been added in the 3.0.0 version of the library.
