### ISSUE TITLE
EPUB 3 support improvements

### ISSUE THREAD

**Issue by vers-one** [vers-one/EpubReader#18]
This is an issue to keep track of the work on the improvements to support EPUB 3 features that are currently not supported.
- [x] Parsing EPUB 3 navigation document
- [x] Parsing EPUB 2 & 3 linear reading order (spine-based text content order)
- [x] General refactoring
- [x] Changes to the examples to work with the new version of the library
- [x] Documentation update

**Comment by tjenniges** [comment]
Thanks! I will test out tonight or tomorrow and give you feedback.

**Comment by vers-one** [comment]
Released in 3.0.0.
