### ISSUE TITLE
PlayOrder not being read

### ISSUE THREAD

**Issue by jflepp** [vers-one/EpubReader#20]
Hello @vers-one,
I think the newest version of the NuGet package doesn't contain the latest version of the assemblies.

When analyzing the assembly in your latest NuGet package I can see that the assembly version is still 2.0.5, despite your adjustions in the project files:

~~~~ csharp
[assembly: TargetFramework(".NETStandard,Version=v1.3", FrameworkDisplayName = "")]
[assembly: AssemblyCompany("vers")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("vers, 2015-2018")]
[assembly: AssemblyFileVersion("2.0.4.0")]
[assembly: AssemblyInformationalVersion("2.0.4")]
[assembly: AssemblyProduct("VersOne.Epub")]
[assembly: AssemblyTitle("VersOne.Epub")]
[assembly: AssemblyVersion("2.0.4.0")]
~~~~

This leads to my pull request not being included:

~~~~ csharp
    internal class Program
    {
        static void Main(string[] args)
        {
            var ePub = EpubReader.ReadBook(@"C:\Users\Jann Flepp\Downloads\Tom Christiansen - Perl Cookbook.epub");

            var points = GetNavigationPoints(ePub.Schema.Navigation.NavMap).ToArray();

            Console.WriteLine("Any playorder null: " + (points.Any(p => p.PlayOrder == null) ? "true" : "false"));
        }

        private static IEnumerable<EpubNavigationPoint> GetNavigationPoints(IEnumerable<EpubNavigationPoint> map)
        {
            foreach (var point in map)
            {
                yield return point;
                foreach (var subPoint in GetNavigationPoints(point.ChildNavigationPoints))
                {
                    yield return subPoint;
                }
            }
        }
    }
~~~~

__With NuGet Package__

`<PackageReference Include="VersOne.Epub" Version="2.0.5" />`

~~~~
Any playorder null: true
~~~~

__With Reference to master branch project__

`<ProjectReference Include="..\VersOne.Epub\VersOne.Epub.csproj" />`

~~~~
Any playorder null: false
~~~~

Could you verify my assumptions?

Thanks for your help!

**Comment by vers-one** [comment]
You are right. Sorry about that!

I repackaged the correct binary as 2.0.5.1 and published it to the NuGet. Could you please verify that it works now?

**Comment by jflepp** [comment]
No problem, I'm glad that you could already solve the issue.
Thank you for your help!

best regards
