### ISSUE TITLE
cover image filename

### ISSUE THREAD

**Issue by lastlink** [vers-one/EpubReader#23]
How do we get the filename of the coverimage? I noticed that in pages that reference it you can find it from the images by the filename. In the epubbook there is the coverimage byte, but there is no filename or mimetype of this.

**Comment by vers-one** [comment]
Check out new `epubBook.Content.Cover` property in v3.0.3.

**Comment by lastlink** [comment]
In epub book I only see  
`AllFiles
Css
Fonts
Html
Images`

I'm using version 3.0.2.
