### ISSUE TITLE
epub parsing error file not found in archive

### ISSUE THREAD

**Issue by lastlink** [vers-one/EpubReader#25]
Something different about the image asset path. file `OEBPS/assets/zr0ggkC.png` was not found in archive.

[tensorflowformachineintelligence.epub.zip](https://github.com/vers-one/EpubReader/files/3454946/tensorflowformachineintelligence.epub.zip)

**Comment by vers-one** [comment]
It is indeed not in the file. You can check this yourself by doing the following:
1. Rename the `tensorflowformachineintelligence.epub` to `tensorflowformachineintelligence.zip`.
2. Unpack the contents of the zip file.
3. Navigate to the `OEBPS/assets` directory and search for the `zr0ggkC.png` file.

**Comment by lastlink** [comment]
Could your library ignore this error?

**Comment by vers-one** [comment]
It doesn't try to read the files in advance when you use `OpenBookAsync` instead of `ReadBookAsync`. I will add an option to ignore the "file not found" errors in the next release.

**Comment by lastlink** [comment]
I changed my `EpubBook epubBook = EpubReader.ReadBook(bookPath);` to `EpubBookRef epubBook = EpubReader.OpenBook(bookPath);`
and was able to resolve this issue

**Comment by vers-one** [comment]
Sorry it took three years but it is finally done! 🙂
The new configuration option is available in v3.2 and the documentation is located [here](https://os.vers.one/EpubReader/malformed-epub/index.html#missing-content-files).
