### ISSUE TITLE
Xamarin forms: Issue with epubreader

### ISSUE THREAD

**Issue by sreejithsree139** [vers-one/EpubReader#33]
I am using [epubreader][1] NuGet package for parsing .epub files. 

My Code:

	string fileName = "SampleEPUB.epub";
	var assembly = typeof(MainPage).GetTypeInfo().Assembly;
	Stream stream = assembly.GetManifestResourceStream($"{assembly.GetName().Name}.{fileName}");
	EpubBook epubBook = EpubReader.ReadBook(stream);
	foreach (EpubNavigationItem chapter in epubBook.Navigation)
	{
		chapterDetails.Add(new ChapterDetails() { title = chapter.Title, htmlData = chapter.HtmlContentFile?.Content, subChapters = chapter.NestedItems });
	}

When parsing the epub file like above, I am getting only one chapter. If I click the chapter there is no data. 

When we open that epub files using Adobe Digital Editions 4.5.11, there are lot of chapters and contents. I need to parse all the chapters and TOC in the epub file.  Please help me to find the issue behind this.

I have added a sample project [here][2] having .epub files for the reference. 

  [1]: https://github.com/vers-one/EpubReader
  [2]: https://drive.google.com/file/d/1BTCHjU3_I7--wjBPQKkVh0XTwphOCZOL/view?usp=sharing

**Comment by vers-one** [comment]
Sorry for a delayed response. You need to use the `EpubBook.ReadingOrder` property. Please take a look at this example: [How to extract the plain text of the whole book](https://github.com/vers-one/EpubReader/tree/master/Source/VersOne.Epub.NetCoreDemo/ExtractPlainText.cs) and let me know if it works for you.
