### ISSUE TITLE
How to read EPUB File from MemoryStream

### ISSUE THREAD

**Issue by KrishnaKPandey** [vers-one/EpubReader#35]
We have developed an application based on this library, now we want to read epub file from MemoryStream. Kindly provide a sample to read a file from memory.

**Comment by timarsha** [comment]
> We have developed an application based on this library, now we want to read epub file from MemoryStream. Kindly provide a sample to read a file from memory.

EpubBook book = await EpubReader.ReadBookAsync(new MemoryStream(byte));

**Comment by vers-one** [comment]
> EpubBook book = await EpubReader.ReadBookAsync(new MemoryStream(byte));

This is indeed a correct answer. Thanks @timarsha!
