### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by SergeySypalo** [vers-one/EpubReader#4]
Hello,

Is it possible to make EpubReader to be used in .NetCore applications?
Thanks for your efforts.

Br,
Sergey Sypalo | Blog at http:\\sypalo.com

**Comment by versfx** [comment]
I am waiting [this](https://github.com/dotnet/corefx/pull/2436) to be merged with .NET Core API before migrating the project to .NET Core. It looks like it is going to be done in Q2 2017 with the release of .NET Core 2.0 Preview.

**Comment by SergeySypalo** [comment]
Gotcha, make sense, thx for the quick reply!

**Comment by ajbeaven** [comment]
Any chance we can leave this open until .NET Core is supported? I'm keen to get updates as I'm waiting on this too.

**Comment by versfx** [comment]
.NET Core 2.0 has been released.
Working on adding support for it.

**Comment by vers-one** [comment]
.NET Core 2.0 support has been implemented in [v2.0](https://github.com/vers-one/EpubReader/releases/tag/v2.0) release.
