### ISSUE TITLE
HTML Parser

### ISSUE THREAD

**Issue by alex-calderwood** [vers-one/EpubReader#42]
Thanks for this library! Very useful in my project. 

My question is: Should I build an HTML parser to display the chapter contents once I have parsed the .epub and have the HTML? The platform I am building for is not one with a built-in HTML/web parser. Any suggestions? Or is there a generally used HTML parsing library? Should this be built into the package?

**Comment by vers-one** [comment]
The content of a .epub book is just a collection of HTML files (along with CSS, images, fonts, etc). You don't need to parse the HTML content to display the book. Instead you need a way to render the HTML in the same way a web browser does.

If you are consuming the HTML content for the purposes other than displaying it, I can recommend https://www.nuget.org/packages/HtmlAgilityPack library.
