### ISSUE TITLE
Unrecognized ePub file

### ISSUE THREAD

**Issue by melinyi** [vers-one/EpubReader#46]
## Description
Unrecognized ePub file

System.AggregateException”(In System.Private.CoreLib.dll )

## Sample EPUB file
File Download Url：

https://drive.google.com/file/d/1zLEv2IL9C8FiLg6T0hm34a5kA-j3IQM3/view?usp=sharing

**Comment by melinyi** [comment]
I can get the information correctly from RolerFileToolkit

[](https://github.com/rolerzhang/RolerFileToolkit)

**Comment by vers-one** [comment]
The file is indeed malformed. If you open `OPS\fb.opf` in the EPUB archive and change the second line from this:
```
<package version="2.0" unique-identifier="PrimaryID" mlns="http://www.idpf.org/2007/opf">
```
to this:
```
<package version="2.0" unique-identifier="PrimaryID" xmlns="http://www.idpf.org/2007/opf">
```
(notice the `xmlns` attribute name instead of `mlns`), it will start working properly.

**Comment by vers-one** [comment]
Closing the stale issue. Please let me know if have any other questions related to this issue.
