### ISSUE TITLE
Error when Epub has not cover

### ISSUE THREAD

**Issue by oguzhandurmaz** [vers-one/EpubReader#75]
## Description
When i try to read epub that has not cover image and any tag for cover in content.opf, throws an exception and can't read epub. If there is image and added in content.opf, it is ok but if there is no cover tag in content.opf, throws an exception

## Exception
`This exception was originally thrown at this call stack:
    VersOne.Epub.Internal.BookCoverReader.ReadEpub2CoverFromGuide(VersOne.Epub.EpubSchema, System.Collections.Generic.Dictionary<string, VersOne.Epub.EpubByteContentFileRef>)
    VersOne.Epub.Internal.BookCoverReader.ReadEpub2Cover(VersOne.Epub.EpubSchema, System.Collections.Generic.Dictionary<string, VersOne.Epub.EpubByteContentFileRef>)
    VersOne.Epub.Internal.BookCoverReader.ReadBookCover(VersOne.Epub.EpubSchema, System.Collections.Generic.Dictionary<string, VersOne.Epub.EpubByteContentFileRef>)
    VersOne.Epub.Internal.ContentReader.ParseContentMap(VersOne.Epub.EpubBookRef, VersOne.Epub.Options.ContentReaderOptions)
    VersOne.Epub.EpubReader.OpenBookAsync.AnonymousMethod__1()
    System.Threading.Tasks.Task<TResult>.InnerInvoke() in Future.cs
    System.Threading.Tasks.Task..cctor.AnonymousMethod__272_0(object) in Task.cs
    System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, object) in ExecutionContext.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs`

**Comment by vers-one** [comment]
@oguzhandurmaz, thank you for reporting this. It might be the same issue as [this one](https://github.com/vers-one/EpubReader/issues/57) which will be fixed in the upcoming 3.3 release. Could you please check if the [3.3.0-alpha1 version](https://www.nuget.org/packages/VersOne.Epub/3.3.0-alpha1) works for you?

**Comment by oguzhandurmaz** [comment]
Yes it worked. Thank you.

**Comment by vers-one** [comment]
Fixed in the [3.3.0 release](https://github.com/vers-one/EpubReader/releases/tag/v3.3.0).
