### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by rubenc57** [vers-one/EpubReader#8]
Hello

I'm trying to install this package and I get this  error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'VersOne.Epub 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

My project is targeting net 4.6.1

Thanks for the help

**Comment by vers-one** [comment]
Hello rubenc57,

Could you please provide the steps to reproduce the issue?

This is what I've tried:
1. Open Visual Studio 2017.
2. Create a console project targeting .NET Framework 4.6.1.
3. Click "Manage Nuget Packages..."
4. Click "Browse", type "VersOne.Epub".
5. Install VersOne.Epub package (the latest version is 2.0.1).
6. Check the Output window to make sure that the installation was successful.

**Comment by SeA75** [comment]
Hello,
same problem:
Could not install package 'VersOne.Epub 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

SO: Win 8.1 Pro
Visual Studio 2015 Upd 3 
NETFramework,Version=v4.6.2

Tnx!
A.

**Comment by vers-one** [comment]
@SeA75, have you installed the [latest Nuget client](https://www.nuget.org/downloads) (3.6.0 for Visual Studio 2015) and [.NET Standard 2.0 Build Support](https://aka.ms/netstandard-build-support-netfx)?

**Comment by vers-one** [comment]
@rubenc57, @SeA75, please try to install the [new version from Nuget](https://www.nuget.org/packages/VersOne.Epub/2.0.2). I replaced the .NET Standard 2.0 target (which is not supported well in Visual Studio 2015) with two separate targets (.NET 4.5 and .NET Core 1.0).

**Comment by zavaree** [comment]
Dear @vers-one 
i try install in vs 2012 . how can i load epub content in richtext for change size text and other action ?

**Comment by vers-one** [comment]
@zavaree, you can see the example how to extract plain text from the epub file here: https://github.com/vers-one/EpubReader#more-examples. But keep in mind that this will get you the plain text without any formatting. If you want to get the HTML of some particular chapter in the epub file, you can do it like this: https://github.com/vers-one/EpubReader#example (see the chapter section).

**Comment by zavaree** [comment]
@vers-one thx for your replay.
How can I, like other programs, resize fonts, mark up text or paging with your code? Will your code be?

**Comment by vers-one** [comment]
This library will give you the HTML and CSS content of the epub file. You will need to do the rendering yourself.
