### ISSUE TITLE
Handling Keys

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#89]
I've talked with you before on this, but I'm really trying to find a foolproof way to handle key mappings. Some books work fine, others have ../ in they keys, some have hardcoded structure of the epub document in the key. 

Like take this situation:
![image](https://github.com/vers-one/EpubReader/assets/735851/6510a44d-c2b7-49df-b262-21afc5b4c43b)

If we were to open the epub, the opf is in ops/
and would have a manifest like:
`<item id="foreword" href="xhtml/foreword.html" media-type="application/xhtml+xml" properties="scripted"/>`
However the nav.xhtml is at root and has:
`<li><a href="ops/xhtml/titlepage.xhtml">Cover</a></li>`

The key provided is ops/xhtml/ch01.html (due to where nav is). 

Is there an option of exposing where the nav is located in the archive so I can correct the keys in post processing mapping?

**Comment by vers-one** [comment]
> Is there an option of exposing where the nav is located in the archive so I can correct the keys in post processing mapping?

It is exposed. In your example you should be able to access the [`EpubBookRef.Content.NavigationHtmlFile` object](https://os.vers.one/EpubReader/reference/VersOne.Epub.EpubContentRef.html#VersOne_Epub_EpubContentRef_NavigationHtmlFile) which has the [`FilePathInEpubArchive` property](https://os.vers.one/EpubReader/reference/VersOne.Epub.EpubContentFileRef.html#VersOne_Epub_EpubContentFileRef_FilePathInEpubArchive). Let me know if this works for you.

**Comment by majora2007** [comment]
This works perfectly, I didn't see the Content.NavigationHtmlFile. Thanks again for the quick reply.
