### ISSUE TITLE
EpubContentFileRef.ReadContentAsTextAsync() missing in v3.3.0

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#90]
Previously I had: 
`await bookFile.ReadContentAsTextAsync()`

now, there doesn't seem to be any way to access the content? 

I didn't see anything in the changelog nor a way to get it from the ContentFileRef.

**Comment by vers-one** [comment]
There was a type name change (`EpubContentFileRef` &rarr; `EpubLocalContentFileRef`) but the method should still be there: [`EpubLocalContentFileRef.ReadContentAsTextAsync()`](https://os.vers.one/EpubReader/reference/VersOne.Epub.EpubLocalContentFileRef.html#VersOne_Epub_EpubLocalContentFileRef_ReadContentAsTextAsync).
